// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using large_fantasy_model.Data;

#nullable disable

namespace large_fantasy_model.Migrations
{
    [DbContext(typeof(LargeFantasyModelContext))]
    [Migration("20260505180251_AddGamePassword")]
    partial class AddGamePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConversationUser", b =>
                {
                    b.Property<int>("ConversationsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ConversationsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ConversationUser");
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GameUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<int>("FriendOfId")
                        .HasColumnType("int");

                    b.Property<int>("FriendsId")
                        .HasColumnType("int");

                    b.HasKey("FriendOfId", "FriendsId");

                    b.HasIndex("FriendsId");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.Additional.CharacterProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Proficiencies");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterDamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterDamageType");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterFeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("FeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("SpellId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("Equipped")
                        .HasColumnType("bit");

                    b.Property<string>("WeaponId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("LastSessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SendingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Resources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IsPublic")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("large_fantasy_model.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminPermissions")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockoutReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConversationUser", b =>
                {
                    b.HasOne("large_fantasy_model.Models.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("large_fantasy_model.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.HasOne("large_fantasy_model.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("large_fantasy_model.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("large_fantasy_model.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FriendOfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("large_fantasy_model.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.Additional.CharacterProficiency", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", "Character")
                        .WithMany("Proficiencies")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.Character", b =>
                {
                    b.HasOne("large_fantasy_model.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.CharacterBackground", "Background", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Background_Description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Background_Name");

                            b1.Property<string>("Option")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Background_Option");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.CharacterCurrency", "Currency", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<int>("Copper")
                                .HasColumnType("int")
                                .HasColumnName("Currency_Copper");

                            b1.Property<int>("Electrum")
                                .HasColumnType("int")
                                .HasColumnName("Currency_Electrum");

                            b1.Property<int>("Gold")
                                .HasColumnType("int")
                                .HasColumnName("Currency_Gold");

                            b1.Property<int>("Platinum")
                                .HasColumnType("int")
                                .HasColumnName("Currency_Platinum");

                            b1.Property<int>("Silver")
                                .HasColumnType("int")
                                .HasColumnName("Currency_Silver");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.CharacterDetails", "Details", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<int>("Age")
                                .HasColumnType("int")
                                .HasColumnName("Details_Age");

                            b1.Property<string>("Backstory")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Backstory");

                            b1.Property<string>("Bond")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Bond");

                            b1.Property<string>("Eyes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Eyes");

                            b1.Property<string>("Flaw")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Flaw");

                            b1.Property<string>("Hair")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Hair");

                            b1.Property<string>("Height")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Height");

                            b1.Property<string>("Ideal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Ideal");

                            b1.Property<string>("Personality")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Personality");

                            b1.Property<string>("Physical")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Physical");

                            b1.Property<string>("Skin")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Details_Skin");

                            b1.Property<int>("Weight")
                                .HasColumnType("int")
                                .HasColumnName("Details_Weight");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.Creature", "Creature", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("int");

                            b1.Property<string>("Alignment")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Inspiration")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Shield")
                                .HasColumnType("bit");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.AbilityScores", "AbilityScores", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Cha")
                                        .HasColumnType("int");

                                    b2.Property<int>("Con")
                                        .HasColumnType("int");

                                    b2.Property<int>("Dex")
                                        .HasColumnType("int");

                                    b2.Property<int>("Int")
                                        .HasColumnType("int");

                                    b2.Property<int>("Str")
                                        .HasColumnType("int");

                                    b2.Property<int>("Wis")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.ArmorClass", "ArmorClass", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.Conditions", "ConditionImmunities", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("Blinded")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Charmed")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Deafened")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Exhausted")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Frightened")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Grappled")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Incapacitated")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Invisible")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Necrotic")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Paralyzed")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Petrified")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Poisoned")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Prone")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Restrained")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Stunned")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Unconscious")
                                        .HasColumnType("bit");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.Conditions", "Conditions", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("Blinded")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Charmed")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Deafened")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Exhausted")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Frightened")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Grappled")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Incapacitated")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Invisible")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Necrotic")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Paralyzed")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Petrified")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Poisoned")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Prone")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Restrained")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Stunned")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Unconscious")
                                        .HasColumnType("bit");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.HitPoints", "HitPoints", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Current")
                                        .HasColumnType("int");

                                    b2.Property<int>("Max")
                                        .HasColumnType("int");

                                    b2.Property<int>("Temporary")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");

                                    b2.OwnsMany("large_fantasy_model.Models.CharacterModels.Additional.Creature.Dice", "Dice", b3 =>
                                        {
                                            b3.Property<int>("HitPointsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<int>("Count")
                                                .HasColumnType("int");

                                            b3.Property<int>("Mod")
                                                .HasColumnType("int");

                                            b3.Property<int>("Sides")
                                                .HasColumnType("int");

                                            b3.HasKey("HitPointsCreatureCharacterId", "Id");

                                            b3.ToTable("Dice");

                                            b3.WithOwner()
                                                .HasForeignKey("HitPointsCreatureCharacterId");
                                        });

                                    b2.Navigation("Dice");
                                });

                            b1.OwnsMany("large_fantasy_model.Models.CharacterModels.Additional.Creature.Language", "Languages", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Language");

                                    b2.HasKey("CreatureCharacterId", "Id");

                                    b2.ToTable("Language");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrows", "SavingThrows", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrowValue", "Cha", b3 =>
                                        {
                                            b3.Property<int>("SavingThrowsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Amount")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SavingThrowsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SavingThrowsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrowValue", "Con", b3 =>
                                        {
                                            b3.Property<int>("SavingThrowsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Amount")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SavingThrowsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SavingThrowsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrowValue", "Dex", b3 =>
                                        {
                                            b3.Property<int>("SavingThrowsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Amount")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SavingThrowsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SavingThrowsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrowValue", "Int", b3 =>
                                        {
                                            b3.Property<int>("SavingThrowsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Amount")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SavingThrowsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SavingThrowsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrowValue", "Str", b3 =>
                                        {
                                            b3.Property<int>("SavingThrowsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Amount")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SavingThrowsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SavingThrowsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SavingThrowValue", "Wis", b3 =>
                                        {
                                            b3.Property<int>("SavingThrowsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Amount")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SavingThrowsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SavingThrowsCreatureCharacterId");
                                        });

                                    b2.Navigation("Cha")
                                        .IsRequired();

                                    b2.Navigation("Con")
                                        .IsRequired();

                                    b2.Navigation("Dex")
                                        .IsRequired();

                                    b2.Navigation("Int")
                                        .IsRequired();

                                    b2.Navigation("Str")
                                        .IsRequired();

                                    b2.Navigation("Wis")
                                        .IsRequired();
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.Senses", "Senses", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SenseValue", "Blindsight", b3 =>
                                        {
                                            b3.Property<int>("SensesCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SensesCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SensesCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SenseValue", "Darkvision", b3 =>
                                        {
                                            b3.Property<int>("SensesCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SensesCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SensesCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SenseValue", "Tremorsense", b3 =>
                                        {
                                            b3.Property<int>("SensesCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SensesCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SensesCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SenseValue", "Truesight", b3 =>
                                        {
                                            b3.Property<int>("SensesCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.HasKey("SensesCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SensesCreatureCharacterId");
                                        });

                                    b2.Navigation("Blindsight")
                                        .IsRequired();

                                    b2.Navigation("Darkvision")
                                        .IsRequired();

                                    b2.Navigation("Tremorsense")
                                        .IsRequired();

                                    b2.Navigation("Truesight")
                                        .IsRequired();
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.Skills", "Skills", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Acrobatics", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "AnimalHandling", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Arcana", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Athletics", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Deception", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "History", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Insight", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Intimidation", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Investigation", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Medicine", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Nature", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Perception", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Performance", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Persuasion", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Religion", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "SleightOfHand", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Stealth", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SkillValue", "Survival", b3 =>
                                        {
                                            b3.Property<int>("SkillsCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Level")
                                                .HasColumnType("int");

                                            b3.HasKey("SkillsCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SkillsCreatureCharacterId");
                                        });

                                    b2.Navigation("Acrobatics")
                                        .IsRequired();

                                    b2.Navigation("AnimalHandling")
                                        .IsRequired();

                                    b2.Navigation("Arcana")
                                        .IsRequired();

                                    b2.Navigation("Athletics")
                                        .IsRequired();

                                    b2.Navigation("Deception")
                                        .IsRequired();

                                    b2.Navigation("History")
                                        .IsRequired();

                                    b2.Navigation("Insight")
                                        .IsRequired();

                                    b2.Navigation("Intimidation")
                                        .IsRequired();

                                    b2.Navigation("Investigation")
                                        .IsRequired();

                                    b2.Navigation("Medicine")
                                        .IsRequired();

                                    b2.Navigation("Nature")
                                        .IsRequired();

                                    b2.Navigation("Perception")
                                        .IsRequired();

                                    b2.Navigation("Performance")
                                        .IsRequired();

                                    b2.Navigation("Persuasion")
                                        .IsRequired();

                                    b2.Navigation("Religion")
                                        .IsRequired();

                                    b2.Navigation("SleightOfHand")
                                        .IsRequired();

                                    b2.Navigation("Stealth")
                                        .IsRequired();

                                    b2.Navigation("Survival")
                                        .IsRequired();
                                });

                            b1.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.Speed", "Speed", b2 =>
                                {
                                    b2.Property<int>("CreatureCharacterId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Walk")
                                        .HasColumnType("int");

                                    b2.HasKey("CreatureCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatureCharacterId");

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SpeedValue", "Burrow", b3 =>
                                        {
                                            b3.Property<int>("SpeedCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Speed")
                                                .HasColumnType("int");

                                            b3.HasKey("SpeedCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SpeedCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SpeedValue", "Climb", b3 =>
                                        {
                                            b3.Property<int>("SpeedCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Speed")
                                                .HasColumnType("int");

                                            b3.HasKey("SpeedCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SpeedCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SpeedValue", "Fly", b3 =>
                                        {
                                            b3.Property<int>("SpeedCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Speed")
                                                .HasColumnType("int");

                                            b3.HasKey("SpeedCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SpeedCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SpeedValue", "Hover", b3 =>
                                        {
                                            b3.Property<int>("SpeedCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Speed")
                                                .HasColumnType("int");

                                            b3.HasKey("SpeedCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SpeedCreatureCharacterId");
                                        });

                                    b2.OwnsOne("large_fantasy_model.Models.CharacterModels.Additional.Creature.SpeedValue", "Swim", b3 =>
                                        {
                                            b3.Property<int>("SpeedCreatureCharacterId")
                                                .HasColumnType("int");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("bit");

                                            b3.Property<int>("Speed")
                                                .HasColumnType("int");

                                            b3.HasKey("SpeedCreatureCharacterId");

                                            b3.ToTable("Characters");

                                            b3.WithOwner()
                                                .HasForeignKey("SpeedCreatureCharacterId");
                                        });

                                    b2.Navigation("Burrow")
                                        .IsRequired();

                                    b2.Navigation("Climb")
                                        .IsRequired();

                                    b2.Navigation("Fly")
                                        .IsRequired();

                                    b2.Navigation("Hover")
                                        .IsRequired();

                                    b2.Navigation("Swim")
                                        .IsRequired();
                                });

                            b1.Navigation("AbilityScores")
                                .IsRequired();

                            b1.Navigation("ArmorClass")
                                .IsRequired();

                            b1.Navigation("ConditionImmunities")
                                .IsRequired();

                            b1.Navigation("Conditions")
                                .IsRequired();

                            b1.Navigation("HitPoints")
                                .IsRequired();

                            b1.Navigation("Languages");

                            b1.Navigation("SavingThrows")
                                .IsRequired();

                            b1.Navigation("Senses")
                                .IsRequired();

                            b1.Navigation("Skills")
                                .IsRequired();

                            b1.Navigation("Speed")
                                .IsRequired();
                        });

                    b.Navigation("Background")
                        .IsRequired();

                    b.Navigation("Creature")
                        .IsRequired();

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterClass", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", null)
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterDamageType", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", "Character")
                        .WithMany("DamageTypes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterEquipment", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", null)
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterFeat", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", null)
                        .WithMany("Feats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterRace", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", "Character")
                        .WithOne("Race")
                        .HasForeignKey("large_fantasy_model.Models.CharacterModels.References.CharacterRace", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterSpell", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", null)
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.References.CharacterWeapon", b =>
                {
                    b.HasOne("large_fantasy_model.Models.CharacterModels.Character", null)
                        .WithMany("Weapons")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("large_fantasy_model.Models.Game", b =>
                {
                    b.HasOne("large_fantasy_model.Models.Conversation", "Conversation")
                        .WithOne("Game")
                        .HasForeignKey("large_fantasy_model.Models.Game", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("large_fantasy_model.Models.User", "User")
                        .WithMany("OwnedGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Message", b =>
                {
                    b.HasOne("large_fantasy_model.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("large_fantasy_model.Models.User", "User")
                        .WithMany("SentMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Resources", b =>
                {
                    b.HasOne("large_fantasy_model.Models.User", "User")
                        .WithMany("Resources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("large_fantasy_model.Models.CharacterModels.Character", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("DamageTypes");

                    b.Navigation("Equipment");

                    b.Navigation("Feats");

                    b.Navigation("Proficiencies");

                    b.Navigation("Race")
                        .IsRequired();

                    b.Navigation("Spells");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("large_fantasy_model.Models.Conversation", b =>
                {
                    b.Navigation("Game");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("large_fantasy_model.Models.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("OwnedGames");

                    b.Navigation("Resources");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
